"""Pydantic request/response models for the GUI setup wizard.

Every model carries ``Field(description=...)`` so the OpenAPI document
generated by FastAPI is self-describing for the Tauri-bundled SPA's typed
client (``apps/web/src/lib/setupClient.ts``). Three-outcome enum fields
(``outcome``, ``next_step``) use ``Literal`` for type-stable codegen.

Alpha-11 contract additions
---------------------------

The folder-import response gained two structured fields after a real-world
SME import surfaced 18 identical "ODA File Converter not installed"
strings inside ``failed: list[str]``:

* :class:`ImportErrorGroup` — same-cause errors coalesced into one entry
  with a ``code``, a remediation hint, and the affected filenames. The
  GUI renders one row per group instead of one per file, and surfaces a
  single actionable fix per category.

* :class:`OdaStatus` — pre-flight detection of the ODA File Converter
  binary (required for ``.dwg`` ingest). Surfaced on the scan response
  so the GUI can warn BEFORE the user kicks off an import that 5% of
  their corpus will be skipped — and on the post-import status response
  so the partial-success panel can offer "install ODA and re-scan" as a
  remediation.

The legacy ``failed: list[str]`` / ``errors: list[str]`` fields stay
populated alongside ``failed_groups`` / ``error_groups`` so an older
pinned frontend bundle running against an alpha-11 backend keeps
working. We will drop the flat lists in alpha-13 once the gauntlet
records 2 releases of green frontend pivots.
"""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field

# Stable machine-readable error codes the frontend uses to pick remediation
# copy / route the partial-success panel. Adding a new code is a
# scoped-tier change; removing one is systemic (frontend has hardcoded
# branches keyed off these strings).
ImportErrorCode = Literal[
    "oda_missing",         # ODA File Converter not installed (DWG ingest)
    "pdf_unreadable",      # pypdf / pdfplumber rejected the file
    "file_locked",         # Windows sharing violation
    "permission_denied",   # Errno 13 / read-only filesystem
    "file_missing",        # path.exists() returned False at import time
    "unsupported_mime",    # dispatcher refused (NotImplementedError)
    "worker_aborted",      # BaseException escaped per-file try/except
    "unknown",             # fall-through; frontend renders raw message
]

# --------------------------------------------------------------------------
# Shared enums
# --------------------------------------------------------------------------

# What the wizard should render next. ``ready`` is the "all required steps
# done — show the Finish button" state; ``complete`` is post-finish.
NextStep = Literal["api_key", "first_project", "first_documents", "ready", "complete"]

# Three-outcome key-validation result. ``unable_to_verify`` covers the
# offline / SDK-import / transient-network case so a flaky network doesn't
# punish the user (mirrors meridian.onboarding.wizard._validate_anthropic_key).
ApiKeyOutcome = Literal["valid", "invalid", "unable_to_verify"]


# --------------------------------------------------------------------------
# /setup/state
# --------------------------------------------------------------------------


class SetupStateResponse(BaseModel):
    """Aggregated wizard progress — driven by the persisted state file."""

    complete: bool = Field(
        description=(
            "True iff the three required steps (api_key, first_project, and "
            "first_documents OR documents_skipped) are all done. Idempotent — "
            "a re-poll never flips back to False."
        )
    )
    api_key_set: bool = Field(
        description=(
            "True if the API key has been validated (or accepted as "
            "'unable_to_verify' for offline installs) and persisted to the OS "
            "keychain."
        )
    )
    first_project_slug: str | None = Field(
        default=None,
        description="Slug of the project the wizard created, or null if not yet created.",
    )
    first_project_name: str | None = Field(
        default=None,
        description="Human-readable name of the wizard-created project, or null.",
    )
    first_project_dir: str | None = Field(
        default=None,
        description=(
            "Absolute path of the projects directory the wizard wrote into "
            "(may differ from settings.projects_dir if the user picked a "
            "custom location). Null until first_project step completes."
        ),
    )
    documents_imported: int = Field(
        default=0,
        description="How many documents the wizard imported (0 if skipped).",
    )
    documents_skipped: bool = Field(
        default=False,
        description="True if the user explicitly skipped the document-import step.",
    )
    next_step: NextStep = Field(
        description=(
            "Which step the GUI should render. 'ready' = all required steps "
            "done but /setup/complete not yet called; 'complete' = wizard "
            "fully finished."
        )
    )


# --------------------------------------------------------------------------
# /setup/api-key
# --------------------------------------------------------------------------


class ApiKeyRequest(BaseModel):
    key: str = Field(
        description=(
            "The Anthropic API key (typically starts with ``sk-ant-``). "
            "Validated against Anthropic's models.list() endpoint."
        ),
        min_length=1,
    )


class ApiKeyResponse(BaseModel):
    outcome: ApiKeyOutcome = Field(
        description=(
            "Three-outcome result. 'valid' = key authenticated; 'invalid' = "
            "Anthropic rejected the key (HTTP 401-style); 'unable_to_verify' "
            "= network / SDK import problem, key tentatively accepted."
        )
    )
    message: str = Field(
        description="PM-language description of the outcome, safe to show in the UI verbatim.",
    )


# --------------------------------------------------------------------------
# /setup/projects
# --------------------------------------------------------------------------


class ProjectCreateRequest(BaseModel):
    name: str = Field(
        description="Human-readable project name (e.g. 'Sydney 2 — Shell CD').",
        min_length=1,
    )
    slug: str = Field(
        description=(
            "File-system-safe slug (e.g. 'syd2-shell-cd'). Becomes the SQLite "
            "filename. The server will validate this matches a slugified form "
            "of the name."
        ),
        min_length=1,
    )
    projects_dir: str = Field(
        description=(
            "Absolute path of the directory under which the SQLite project "
            "file should be created. Must be writeable. The wizard sets this "
            "once on first project create; subsequent projects inherit."
        ),
        min_length=1,
    )


class ProjectCreateResponse(BaseModel):
    created: bool = Field(
        description="True on a successful new-project create.",
    )
    slug: str = Field(description="The slug under which the project was created.")
    db_path: str = Field(
        description="Absolute path to the project's SQLite file.",
    )


class ProjectExistsErrorResponse(BaseModel):
    """409 body when a project at the given slug already exists."""

    error: Literal["slug_exists"] = Field(
        description="Stable machine-readable error code for client routing.",
    )
    existing_db_path: str = Field(
        description=(
            "Path to the existing SQLite file so the GUI can offer 'Open it' "
            "rather than forcing the user to pick a different slug."
        ),
    )


class ProjectsDirNotWriteableResponse(BaseModel):
    """400 body when ``projects_dir`` cannot be created or written to."""

    error: Literal["projects_dir_not_writeable"] = Field(
        description="Stable machine-readable error code.",
    )
    message: str = Field(
        description="PM-language description of why the path was rejected.",
    )


# --------------------------------------------------------------------------
# /setup/import
# --------------------------------------------------------------------------


class ImportRequest(BaseModel):
    project_slug: str = Field(
        description="Slug of the project to import documents into. Must already exist.",
        min_length=1,
    )
    paths: list[str] = Field(
        description="Absolute paths of files to import (PDF, DOCX, XLSX, EML/MSG, DWG).",
        min_length=1,
    )


class ImportJobResponse(BaseModel):
    job_id: str = Field(
        description=(
            "Opaque job ID. Poll ``GET /setup/import/{job_id}`` until "
            "``status='succeeded' | 'failed'``."
        )
    )


class ImportErrorEntry(BaseModel):
    """One per-file failure inside an import job.

    Replaces the alpha-10-and-earlier ``errors: list[str]`` of opaque
    "{filename}: {message}" strings. The frontend uses ``code`` to route
    rendering (which icon, which remediation copy) and ``file`` /
    ``message`` for the audit list.
    """

    code: ImportErrorCode = Field(
        description=(
            "Stable machine-readable code. New values are added in scoped "
            "releases; removing one is a frontend-breaking change."
        ),
    )
    file: str = Field(
        description="Basename of the failing file (no absolute path leaked to UI).",
    )
    message: str = Field(
        description=(
            "Underlying error message verbatim. Safe to render: the import "
            "worker only constructs these from caught exceptions whose "
            "messages are themselves user-facing."
        ),
    )


class ImportErrorGroup(BaseModel):
    """Same-code errors coalesced into one row.

    Alpha-11 finding: 18 identical 800-byte strings for "ODA File Converter
    not installed" wasted bytes and was unreadable. Coalesced groups
    surface "18 .dwg files were skipped — install ODA File Converter to
    enable DWG ingest" as one row with an expandable file list.
    """

    code: ImportErrorCode = Field(
        description="The shared error code for every entry in this group.",
    )
    count: int = Field(
        ge=1,
        description="Number of files in the group.",
    )
    summary: str = Field(
        description=(
            "PM-language one-liner ('18 AutoCAD drawings were skipped'). "
            "Generated server-side so frontend rendering is one consistent "
            "string regardless of which client is reading."
        ),
    )
    remediation: str = Field(
        description=(
            "Specific user action that resolves this category. PM-language. "
            "Empty string (NOT null) when no remediation applies (e.g. "
            "code='unknown')."
        ),
    )
    files: list[str] = Field(
        default_factory=list,
        description=(
            "Basenames of every file in this group. The GUI renders this as "
            "an expandable list; capped at 100 server-side to keep the "
            "response payload bounded."
        ),
    )
    truncated: bool = Field(
        default=False,
        description=(
            "True when the file list was truncated to the 100-entry cap. "
            "GUI surfaces 'and N more' when set."
        ),
    )


class ImportJobStatusResponse(BaseModel):
    """Mirrors the shape of ``GET /projects/{name}/jobs/{job_id}`` enough that
    the GUI can reuse the same poll loop component."""

    job_id: str = Field(description="The job ID echoed back.")
    status: Literal["pending", "running", "succeeded", "failed"] = Field(
        description="Three-plus-one-outcome state machine.",
    )
    total: int = Field(description="Number of files queued.")
    completed: int = Field(description="Number of files finished (success + dedup + error).")
    imported: int = Field(description="Number of files genuinely imported (excludes dedup).")
    deduped: int = Field(description="Number of files skipped because content_hash already present.")
    errors: list[str] = Field(
        default_factory=list,
        description=(
            "DEPRECATED in alpha-11: kept populated for one release so a "
            "pinned alpha-10-or-earlier frontend bundle keeps rendering. "
            "Use ``error_groups`` instead. Will be removed in alpha-13."
        ),
    )
    error_groups: list[ImportErrorGroup] = Field(
        default_factory=list,
        description=(
            "Coalesced view of ``errors`` — same data, grouped by error "
            "code with PM-language summary and remediation."
        ),
    )


class ImportSkipRequest(BaseModel):
    project_slug: str = Field(
        description="Slug of the project the user is skipping document import for.",
        min_length=1,
    )


class ImportSkipResponse(BaseModel):
    acknowledged: Literal[True] = Field(
        description="Always true on success — the call is idempotent.",
    )


# --------------------------------------------------------------------------
# /setup/import-folder/scan + /setup/import-folder
# --------------------------------------------------------------------------
#
# Round-18: PMs don't think in files; they think in project folders. The
# scan endpoint produces a manifest the GUI renders as "we found X PDFs,
# Y DOCXs, Z DWGs in this folder; ingest all of them?"; the import
# endpoint kicks off the actual ingest job. Both are reusable beyond the
# wizard (e.g. CLI ``meridian projects scan-folder``).


class FolderScanRequest(BaseModel):
    folder_path: str = Field(
        description=(
            "Absolute path of the folder to scan. The server walks it "
            "recursively, classifies files by extension, and returns a "
            "manifest. No DB writes."
        ),
        min_length=1,
    )


class FolderSkipEntry(BaseModel):
    path: str = Field(description="Absolute path of the skipped file.")
    reason: Literal[
        "unsupported_extension",
        "access_denied",
        "hidden_or_system",
    ] = Field(
        description=(
            "Why the file was skipped. Stable enum so the GUI can render "
            "filter chips ('show 12 unsupported files', etc.) and group "
            "the audit list."
        )
    )


class OdaStatus(BaseModel):
    """ODA File Converter availability — pre-flight detection for DWG ingest.

    Alpha-11 finding: an SME's first import silently failed on every
    ``.dwg`` because ODA isn't bundled with the installer. This response
    field lets the GUI warn upfront ("18 of your 347 files are AutoCAD
    drawings; install ODA File Converter to ingest them") instead of
    burying the same error 18 times in a post-import ``failed[]`` list.

    Fields:

    * ``available`` — True iff ``meridian.ingest.dwg.oda_available()``
      located the binary via the env var, PATH, or default Windows
      install glob.
    * ``version`` — best-effort parsed version string. None when
      unavailable OR when the binary refuses ``--version`` (older
      releases). Don't render as a gate — render as a footnote.
    * ``install_url`` — the canonical URL for the installer download.
      Constant per release; surfaced in this field so the frontend
      doesn't hardcode it (one place to change if ODA's hosting moves).
    * ``binary_path`` — absolute path of the located binary, or null
      when unavailable. Surfaced for ops/debug; the GUI shows it as
      a small "found at: ..." line under the green tick.
    """

    available: bool = Field(
        description="True iff ODA File Converter was located.",
    )
    version: str | None = Field(
        default=None,
        description="Best-effort version string ('25.4.0'). May be null.",
    )
    install_url: str = Field(
        description=(
            "Canonical installer URL surfaced in remediation copy. "
            "Frontend should not hardcode this."
        ),
    )
    binary_path: str | None = Field(
        default=None,
        description="Absolute path of the located binary, or null when unavailable.",
    )


class FolderScanResponse(BaseModel):
    folder_path: str = Field(description="Resolved (absolute) folder path the scan ran against.")
    folder_name: str = Field(
        description=(
            "The folder's basename (e.g. ``Shell-C-D``). Used by the GUI as "
            "the default project-name suggestion before slugification."
        )
    )
    files_by_kind: dict[str, list[str]] = Field(
        description=(
            "Bucketed file paths by kind (``pdf``, ``docx``, ``xlsx``, "
            "``dwg``, ``eml``, ``msg``). Every supported kind is always "
            "present as a key — empty list when no files of that kind."
        )
    )
    skipped: list[FolderSkipEntry] = Field(
        default_factory=list,
        description=(
            "Files the walker found but did not classify as ingestable. "
            "Used by the GUI to surface 'we ignored these and why' before "
            "the user presses Import."
        ),
    )
    total_ingestable: int = Field(
        description="Sum of the lengths of files_by_kind — convenience for the GUI.",
    )
    oda: OdaStatus = Field(
        description=(
            "Pre-flight ODA File Converter availability. The GUI uses this "
            "to render an upfront 'install ODA to ingest these N drawings' "
            "callout when files_by_kind.dwg is non-empty and "
            "oda.available is False, instead of letting the user hit the "
            "failure mid-import."
        ),
    )


class FolderImportRequest(BaseModel):
    folder_path: str = Field(
        description=(
            "Absolute folder path to ingest. Server re-walks the folder "
            "(idempotent — content_hash dedup is handled in ingest_file)."
        ),
        min_length=1,
    )
    project_name: str = Field(
        description=(
            "Human-readable project name. The server slugifies it via "
            "``meridian.projects._slugify`` to determine the SQLite "
            "filename. The project must already exist (use "
            "``POST /setup/projects`` first)."
        ),
        min_length=1,
    )


class FolderImportJobStatusResponse(BaseModel):
    """Per-file progress for a folder-import job.

    Same shape as :class:`ImportJobStatusResponse` plus the in-flight
    ``current_file`` field so the GUI can render
    ``"Importing 03_HVAC_Spec.pdf… (8 of 47)"``.

    Alpha-11 added ``failed_groups`` and ``oda`` so the post-import UI
    can route remediation by error category (rather than rendering 18
    identical "ODA not installed" strings) and offer "install ODA and
    re-scan" as a one-click recovery affordance.
    """

    job_id: str = Field(description="The job ID echoed back.")
    status: Literal["pending", "running", "succeeded", "failed"] = Field(
        description="Three-plus-one-outcome state machine.",
    )
    total: int = Field(description="Number of files queued.")
    completed: int = Field(description="Number of files finished (success + dedup + error).")
    imported: int = Field(description="Number of files genuinely imported (excludes dedup).")
    deduped: int = Field(description="Number of files skipped because content_hash already present.")
    failed: list[str] = Field(
        default_factory=list,
        description=(
            "DEPRECATED in alpha-11: kept populated for one release so a "
            "pinned alpha-10-or-earlier frontend bundle keeps rendering. "
            "Use ``failed_groups`` instead. Will be removed in alpha-13."
        ),
    )
    failed_groups: list[ImportErrorGroup] = Field(
        default_factory=list,
        description=(
            "Coalesced view of ``failed`` — same data, grouped by error "
            "code with PM-language summary and remediation. Empty when "
            "no failures occurred."
        ),
    )
    current_file: str | None = Field(
        default=None,
        description=(
            "Absolute path of the file the worker is mid-ingest on, or null "
            "when the job is between files / finished."
        ),
    )
    oda: OdaStatus = Field(
        description=(
            "ODA File Converter availability re-checked at status-poll time. "
            "Lets the GUI offer 'install ODA and re-scan' as a remediation "
            "in the partial-success panel without needing a separate probe "
            "endpoint."
        ),
    )


# --------------------------------------------------------------------------
# /setup/projects/suggest-name
# --------------------------------------------------------------------------


class SuggestNameRequest(BaseModel):
    folder_path: str = Field(
        description=(
            "Absolute folder path. The server uses the folder basename as "
            "the seed for slugification and checks for an existing project "
            "with that slug."
        ),
        min_length=1,
    )


class SuggestNameResponse(BaseModel):
    suggested_name: str = Field(
        description=(
            "Slugified candidate project name. If no project exists at the "
            "naive slug, this matches it; otherwise a numeric suffix (-2, "
            "-3, …) is appended until uniqueness."
        )
    )
    is_available: bool = Field(
        description=(
            "True when the naive (un-suffixed) slug is free; False when the "
            "server had to bump the suffix."
        )
    )


# --------------------------------------------------------------------------
# /setup/complete
# --------------------------------------------------------------------------


class SetupCompleteResponse(SetupStateResponse):
    """Same shape as /setup/state — flipping ``complete=True`` is the only
    meaningful side effect, but returning the full state lets the GUI skip
    a follow-up GET."""


class RuntimeStatusResponse(BaseModel):
    """Operator-facing runtime introspection — alpha-12.

    Triage on a slow / hung / silent backend used to require crawling
    Get-Process + Get-NetTCPConnection + reading log paths the user
    had to know. This endpoint surfaces the same data the backend
    already knows. It is intentionally cheap (no DB queries, no file I/O
    beyond os.getpid) so it stays callable even when the backend is
    under load.

    Why this exists: alpha-11's "documents uploaded then web interface
    broke" triage took 20+ minutes because we had to ask the operator
    to run 4 PowerShell probes to learn things the backend already
    knew (pid, uptime, log paths, last activity). Surface them.
    """

    pid: int = Field(description="OS process ID of this uvicorn worker.")
    started_at: str = Field(
        description="ISO-8601 UTC timestamp of process start.",
    )
    uptime_seconds: float = Field(
        description="Seconds since the process started.",
    )
    version: str = Field(description="Meridian package version (matches /health.version).")
    python_version: str = Field(
        description="CPython version (e.g. '3.12.8') for compatibility triage.",
    )
    platform: str = Field(
        description="OS platform string (e.g. 'win32', 'linux', 'darwin').",
    )
    backend_log_path: str | None = Field(
        default=None,
        description=(
            "Absolute path of the operator-visible backend.log if the "
            "MERIDIAN_BACKEND_LOG env var is set (the installer sets it). "
            "Null when running outside the canonical install layout (dev "
            "tree, gauntlet venv, etc.)."
        ),
    )
    structlog_dir: str | None = Field(
        default=None,
        description=(
            "Absolute path of the directory holding the per-project "
            "JSON-lines structlog files. Null until configure_logging "
            "has run."
        ),
    )
    last_import_job: dict | None = Field(
        default=None,
        description=(
            "Snapshot of the most-recent folder-import job, if any: "
            "{job_id, status, completed, total, last_activity_age_s}. "
            "Null when no job has been kicked this process. Lets a "
            "triage flow answer 'is the worker stuck?' from one HTTP call."
        ),
    )
    auth_disabled: bool = Field(
        description=(
            "Alpha-13: True iff MERIDIAN_AUTH_DISABLED=1 is set and "
            "require_session is short-circuited. The frontend renders a "
            "loud debug-mode banner when this is true so an operator "
            "cannot ship a production build with the bypass on without "
            "noticing. Always present (never null) so the GUI's banner "
            "logic doesn't need an undefined-check."
        ),
    )


class SetupDefaultsResponse(BaseModel):
    """Server-side defaults the frontend pre-fills into form fields.

    Two real, server-resolved paths so the frontend never has to substitute
    placeholder tokens like ``C:\\Users\\<you>\\...`` (the alpha-5 bug
    class — frontend submitted the literal ``<you>`` string and Windows
    path validation rejected the ``<`` and ``>``). Both fields are real
    paths the backend's ``Path()`` constructor can parse without raising.

    * ``projects_dir`` — where the wizard should create new project SQLite
      files (resolves via the same ``_meridian_home()`` chain everything
      else uses: ``MERIDIAN_HOME`` env var, then ``C:\\Meridian`` on
      Windows when present, then ``~/Meridian``, with ``/projects``
      appended).
    * ``home_dir`` — the running OS user's home directory
      (``str(Path.home())``). Alpha-9 added this so the first-documents
      page can build a smart pre-fill for its typed-path input
      (``<home_dir>\\Documents\\<folderName>``) when the browser
      webkitdirectory picker only returns the folder name. Browser
      security hides the absolute path from JS; the Tauri MSI (round 18)
      eliminates this restriction entirely.
    """

    projects_dir: str = Field(
        description=(
            "Absolute path the wizard pre-fills into the first-project "
            "form. Always a real path with no placeholder tokens."
        ),
        min_length=1,
    )
    home_dir: str = Field(
        description=(
            "Running OS user's home directory (str(Path.home())). The "
            "first-documents page uses it to build a smart typed-path "
            "pre-fill of <home_dir>\\Documents\\<folderName> when the "
            "browser folder-picker only exposes the folder name."
        ),
        min_length=1,
    )


__all__ = [
    "ApiKeyOutcome",
    "ApiKeyRequest",
    "ApiKeyResponse",
    "FolderImportJobStatusResponse",
    "FolderImportRequest",
    "FolderScanRequest",
    "FolderScanResponse",
    "FolderSkipEntry",
    "ImportErrorCode",
    "ImportErrorEntry",
    "ImportErrorGroup",
    "ImportJobResponse",
    "ImportJobStatusResponse",
    "ImportRequest",
    "ImportSkipRequest",
    "ImportSkipResponse",
    "NextStep",
    "OdaStatus",
    "ProjectCreateRequest",
    "ProjectCreateResponse",
    "ProjectExistsErrorResponse",
    "ProjectsDirNotWriteableResponse",
    "RuntimeStatusResponse",
    "SetupCompleteResponse",
    "SetupDefaultsResponse",
    "SetupStateResponse",
    "SuggestNameRequest",
    "SuggestNameResponse",
]
