"""Pydantic request/response models for the GUI setup wizard.

Every model carries ``Field(description=...)`` so the OpenAPI document
generated by FastAPI is self-describing for the Tauri-bundled SPA's typed
client (``apps/web/src/lib/setupClient.ts``). Three-outcome enum fields
(``outcome``, ``next_step``) use ``Literal`` for type-stable codegen.
"""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field

# --------------------------------------------------------------------------
# Shared enums
# --------------------------------------------------------------------------

# What the wizard should render next. ``ready`` is the "all required steps
# done — show the Finish button" state; ``complete`` is post-finish.
NextStep = Literal["api_key", "first_project", "first_documents", "ready", "complete"]

# Three-outcome key-validation result. ``unable_to_verify`` covers the
# offline / SDK-import / transient-network case so a flaky network doesn't
# punish the user (mirrors meridian.onboarding.wizard._validate_anthropic_key).
ApiKeyOutcome = Literal["valid", "invalid", "unable_to_verify"]


# --------------------------------------------------------------------------
# /setup/state
# --------------------------------------------------------------------------


class SetupStateResponse(BaseModel):
    """Aggregated wizard progress — driven by the persisted state file."""

    complete: bool = Field(
        description=(
            "True iff the three required steps (api_key, first_project, and "
            "first_documents OR documents_skipped) are all done. Idempotent — "
            "a re-poll never flips back to False."
        )
    )
    api_key_set: bool = Field(
        description=(
            "True if the API key has been validated (or accepted as "
            "'unable_to_verify' for offline installs) and persisted to the OS "
            "keychain."
        )
    )
    first_project_slug: str | None = Field(
        default=None,
        description="Slug of the project the wizard created, or null if not yet created.",
    )
    first_project_name: str | None = Field(
        default=None,
        description="Human-readable name of the wizard-created project, or null.",
    )
    first_project_dir: str | None = Field(
        default=None,
        description=(
            "Absolute path of the projects directory the wizard wrote into "
            "(may differ from settings.projects_dir if the user picked a "
            "custom location). Null until first_project step completes."
        ),
    )
    documents_imported: int = Field(
        default=0,
        description="How many documents the wizard imported (0 if skipped).",
    )
    documents_skipped: bool = Field(
        default=False,
        description="True if the user explicitly skipped the document-import step.",
    )
    next_step: NextStep = Field(
        description=(
            "Which step the GUI should render. 'ready' = all required steps "
            "done but /setup/complete not yet called; 'complete' = wizard "
            "fully finished."
        )
    )


# --------------------------------------------------------------------------
# /setup/api-key
# --------------------------------------------------------------------------


class ApiKeyRequest(BaseModel):
    key: str = Field(
        description=(
            "The Anthropic API key (typically starts with ``sk-ant-``). "
            "Validated against Anthropic's models.list() endpoint."
        ),
        min_length=1,
    )


class ApiKeyResponse(BaseModel):
    outcome: ApiKeyOutcome = Field(
        description=(
            "Three-outcome result. 'valid' = key authenticated; 'invalid' = "
            "Anthropic rejected the key (HTTP 401-style); 'unable_to_verify' "
            "= network / SDK import problem, key tentatively accepted."
        )
    )
    message: str = Field(
        description="PM-language description of the outcome, safe to show in the UI verbatim.",
    )


# --------------------------------------------------------------------------
# /setup/projects
# --------------------------------------------------------------------------


class ProjectCreateRequest(BaseModel):
    name: str = Field(
        description="Human-readable project name (e.g. 'Sydney 2 — Shell CD').",
        min_length=1,
    )
    slug: str = Field(
        description=(
            "File-system-safe slug (e.g. 'syd2-shell-cd'). Becomes the SQLite "
            "filename. The server will validate this matches a slugified form "
            "of the name."
        ),
        min_length=1,
    )
    projects_dir: str = Field(
        description=(
            "Absolute path of the directory under which the SQLite project "
            "file should be created. Must be writeable. The wizard sets this "
            "once on first project create; subsequent projects inherit."
        ),
        min_length=1,
    )


class ProjectCreateResponse(BaseModel):
    created: bool = Field(
        description="True on a successful new-project create.",
    )
    slug: str = Field(description="The slug under which the project was created.")
    db_path: str = Field(
        description="Absolute path to the project's SQLite file.",
    )


class ProjectExistsErrorResponse(BaseModel):
    """409 body when a project at the given slug already exists."""

    error: Literal["slug_exists"] = Field(
        description="Stable machine-readable error code for client routing.",
    )
    existing_db_path: str = Field(
        description=(
            "Path to the existing SQLite file so the GUI can offer 'Open it' "
            "rather than forcing the user to pick a different slug."
        ),
    )


class ProjectsDirNotWriteableResponse(BaseModel):
    """400 body when ``projects_dir`` cannot be created or written to."""

    error: Literal["projects_dir_not_writeable"] = Field(
        description="Stable machine-readable error code.",
    )
    message: str = Field(
        description="PM-language description of why the path was rejected.",
    )


# --------------------------------------------------------------------------
# /setup/import
# --------------------------------------------------------------------------


class ImportRequest(BaseModel):
    project_slug: str = Field(
        description="Slug of the project to import documents into. Must already exist.",
        min_length=1,
    )
    paths: list[str] = Field(
        description="Absolute paths of files to import (PDF, DOCX, XLSX, EML/MSG, DWG).",
        min_length=1,
    )


class ImportJobResponse(BaseModel):
    job_id: str = Field(
        description=(
            "Opaque job ID. Poll ``GET /setup/import/{job_id}`` until "
            "``status='succeeded' | 'failed'``."
        )
    )


class ImportJobStatusResponse(BaseModel):
    """Mirrors the shape of ``GET /projects/{name}/jobs/{job_id}`` enough that
    the GUI can reuse the same poll loop component."""

    job_id: str = Field(description="The job ID echoed back.")
    status: Literal["pending", "running", "succeeded", "failed"] = Field(
        description="Three-plus-one-outcome state machine.",
    )
    total: int = Field(description="Number of files queued.")
    completed: int = Field(description="Number of files finished (success + dedup + error).")
    imported: int = Field(description="Number of files genuinely imported (excludes dedup).")
    deduped: int = Field(description="Number of files skipped because content_hash already present.")
    errors: list[str] = Field(
        default_factory=list,
        description="Per-file error strings; empty if status != 'failed'.",
    )


class ImportSkipRequest(BaseModel):
    project_slug: str = Field(
        description="Slug of the project the user is skipping document import for.",
        min_length=1,
    )


class ImportSkipResponse(BaseModel):
    acknowledged: Literal[True] = Field(
        description="Always true on success — the call is idempotent.",
    )


# --------------------------------------------------------------------------
# /setup/import-folder/scan + /setup/import-folder
# --------------------------------------------------------------------------
#
# Round-18: PMs don't think in files; they think in project folders. The
# scan endpoint produces a manifest the GUI renders as "we found X PDFs,
# Y DOCXs, Z DWGs in this folder; ingest all of them?"; the import
# endpoint kicks off the actual ingest job. Both are reusable beyond the
# wizard (e.g. CLI ``meridian projects scan-folder``).


class FolderScanRequest(BaseModel):
    folder_path: str = Field(
        description=(
            "Absolute path of the folder to scan. The server walks it "
            "recursively, classifies files by extension, and returns a "
            "manifest. No DB writes."
        ),
        min_length=1,
    )


class FolderSkipEntry(BaseModel):
    path: str = Field(description="Absolute path of the skipped file.")
    reason: Literal[
        "unsupported_extension",
        "access_denied",
        "hidden_or_system",
    ] = Field(
        description=(
            "Why the file was skipped. Stable enum so the GUI can render "
            "filter chips ('show 12 unsupported files', etc.) and group "
            "the audit list."
        )
    )


class FolderScanResponse(BaseModel):
    folder_path: str = Field(description="Resolved (absolute) folder path the scan ran against.")
    folder_name: str = Field(
        description=(
            "The folder's basename (e.g. ``Shell-C-D``). Used by the GUI as "
            "the default project-name suggestion before slugification."
        )
    )
    files_by_kind: dict[str, list[str]] = Field(
        description=(
            "Bucketed file paths by kind (``pdf``, ``docx``, ``xlsx``, "
            "``dwg``, ``eml``, ``msg``). Every supported kind is always "
            "present as a key — empty list when no files of that kind."
        )
    )
    skipped: list[FolderSkipEntry] = Field(
        default_factory=list,
        description=(
            "Files the walker found but did not classify as ingestable. "
            "Used by the GUI to surface 'we ignored these and why' before "
            "the user presses Import."
        ),
    )
    total_ingestable: int = Field(
        description="Sum of the lengths of files_by_kind — convenience for the GUI.",
    )


class FolderImportRequest(BaseModel):
    folder_path: str = Field(
        description=(
            "Absolute folder path to ingest. Server re-walks the folder "
            "(idempotent — content_hash dedup is handled in ingest_file)."
        ),
        min_length=1,
    )
    project_name: str = Field(
        description=(
            "Human-readable project name. The server slugifies it via "
            "``meridian.projects._slugify`` to determine the SQLite "
            "filename. The project must already exist (use "
            "``POST /setup/projects`` first)."
        ),
        min_length=1,
    )


class FolderImportJobStatusResponse(BaseModel):
    """Per-file progress for a folder-import job.

    Same shape as :class:`ImportJobStatusResponse` plus the in-flight
    ``current_file`` field so the GUI can render
    ``"Importing 03_HVAC_Spec.pdf… (8 of 47)"``.
    """

    job_id: str = Field(description="The job ID echoed back.")
    status: Literal["pending", "running", "succeeded", "failed"] = Field(
        description="Three-plus-one-outcome state machine.",
    )
    total: int = Field(description="Number of files queued.")
    completed: int = Field(description="Number of files finished (success + dedup + error).")
    imported: int = Field(description="Number of files genuinely imported (excludes dedup).")
    deduped: int = Field(description="Number of files skipped because content_hash already present.")
    failed: list[str] = Field(
        default_factory=list,
        description=(
            "Per-file error strings; surfaced as a list so the GUI can render "
            "each one inline with its source filename."
        ),
    )
    current_file: str | None = Field(
        default=None,
        description=(
            "Absolute path of the file the worker is mid-ingest on, or null "
            "when the job is between files / finished."
        ),
    )


# --------------------------------------------------------------------------
# /setup/projects/suggest-name
# --------------------------------------------------------------------------


class SuggestNameRequest(BaseModel):
    folder_path: str = Field(
        description=(
            "Absolute folder path. The server uses the folder basename as "
            "the seed for slugification and checks for an existing project "
            "with that slug."
        ),
        min_length=1,
    )


class SuggestNameResponse(BaseModel):
    suggested_name: str = Field(
        description=(
            "Slugified candidate project name. If no project exists at the "
            "naive slug, this matches it; otherwise a numeric suffix (-2, "
            "-3, …) is appended until uniqueness."
        )
    )
    is_available: bool = Field(
        description=(
            "True when the naive (un-suffixed) slug is free; False when the "
            "server had to bump the suffix."
        )
    )


# --------------------------------------------------------------------------
# /setup/complete
# --------------------------------------------------------------------------


class SetupCompleteResponse(SetupStateResponse):
    """Same shape as /setup/state — flipping ``complete=True`` is the only
    meaningful side effect, but returning the full state lets the GUI skip
    a follow-up GET."""


__all__ = [
    "ApiKeyOutcome",
    "ApiKeyRequest",
    "ApiKeyResponse",
    "FolderImportJobStatusResponse",
    "FolderImportRequest",
    "FolderScanRequest",
    "FolderScanResponse",
    "FolderSkipEntry",
    "ImportJobResponse",
    "ImportJobStatusResponse",
    "ImportRequest",
    "ImportSkipRequest",
    "ImportSkipResponse",
    "NextStep",
    "ProjectCreateRequest",
    "ProjectCreateResponse",
    "ProjectExistsErrorResponse",
    "ProjectsDirNotWriteableResponse",
    "SetupCompleteResponse",
    "SetupStateResponse",
    "SuggestNameRequest",
    "SuggestNameResponse",
]
